Разметка всех страниц
htmlacademy-htmlcss/1765393-sedona-37 pull request #2
Opened 2023-06-04 23:36 UTC by nknina

2023-06-12 13:15 UTC, Ankhena requested changes

2023-06-12 13:15 UTC, Ankhena commented on index.html
> +
![2023-06-12_15-37-14](https://github.com/htmlacademy-htmlcss/1765393-sedona-37/assets/20879307/01062cdd-d2f0-46ad-bbeb-bd1f0185ad12)
Нет смысла грузить пользователю две одинаковые картинки. Достаточно по одному экземпляру. 

По этой же причине не удобно разбивать картинки по страницам. Но зато удобно группировать по смыслу. 
Например. папка social-icons для иконок соц сетей. Ведь они могут быть использованы на любой странице. А также находится и в футере и в хедере, а также в теле страницы. 

Пересмотри наши созвоны, я рассказывала об этом.

2023-06-12 13:15 UTC, Ankhena commented on index.html
> +          <li class="navigation-item">
Логотип не является элементом списка меню. 
Но, по желанию, может быть включен в nav.

2023-06-12 13:15 UTC, Ankhena commented on index.html
> +          </li>
```suggestion
          <li class="navigation-item">
            <a class="navigation-link navigation-link-current" href="index.html" aria-current="page">Главная</a>
          </li>
```

Как так вышло, что логотип является ссылкой на главную и она index.html, а ссылка на главную ссылается уже на какой-то неизвестный page.html?

2023-06-12 13:15 UTC, Ankhena commented on index.html
> +          </li>
```suggestion
          <li class="navigation-item">
            <a class="navigation-link" href="#">О Седоне</a>
          </li>
```
Не придумывай страниц. 
Если не знаем куда ведет ссылка, просто ставим `#`. 
Представь, что ты взяла верстку и тебе нужно из неё сделать реальный сайт. И все ссылки заменить на настоящие. Можно быстренько по поиску найти все решетки, а можно мучительно глазами искать и читать все ссылки и проверять они ведут уже куда надо или они неверные.

2023-06-12 13:15 UTC, Ankhena commented on index.html
> +          </li>
```suggestion
          <li class="navigation-item">
            <a class="navigation-link" href="catalog.html">Гостиницы</a>
          </li>
```
Ты ведь сама назвала файл с версткой гостиниц `catalog.html`. А хочешь, чтобы браузер отобразил hotel.html

2023-06-12 13:15 UTC, Ankhena commented on index.html
> +            <a class="navigation-link" href="#">
Вот тут с решетками отлично

2023-06-12 13:15 UTC, Ankhena commented on index.html
> +          </li>
```suggestion
          <li class="navigation-item">
            <a class="navigation-link" href="#">
              <span class="visually-hidden">Отелей в избранном: </span>
              <span class="user-vaforites">12</span>
            </a>
          </li>
```
Помнишь, в школе учили полностью писать ответ в задаче? Тут примерно аналогично. 
Конечно, нужно применять разумный подход, чтобы не получить масло масляное или что-то непонятное.

2023-06-12 13:15 UTC, Ankhena commented on index.html
> +          </li>
```suggestion
          <li class="navigation-item">
            <a class="button navigation-link" href="#">Хочу сюда!</a>
          </li>
```
Текст в коде мы всегда должны писать по правилам языка страницы. 
По-русски фразы пишутся с большой буквы и потом маленькие. 
Если по дизайну нужно, чтобы все были заглавными, то меняем это стилями и text-transform.

2023-06-12 13:15 UTC, Ankhena commented on index.html
> +            <p class="advantages-item-content advantages-white">Седона - не аттракцион для<br>туристов, там течёт
Пока не нужно ставить br
Ведь может быть текст и так ляжет по макету, когда мы зададим правильные размеры.

2023-06-12 13:15 UTC, Ankhena commented on index.html
> +            </svg>
```suggestion

```
Нет смысла вставлять эти svg в разметку. 
Они очень удобно добавятся стилями.
Смысла в них нет, цвета менять не нужно => нечего им загрязнять код и ухудшать его читаемость.

2023-06-12 13:15 UTC, Ankhena commented on index.html
> +        <button class="button interested-button" type="button">Поиск гостиницы в Седоне</button>
```suggestion
        <a class="button interested-button" href="#">Поиск гостиницы в Седоне</a>
```
Это ссылка, которая куда-то ведет.
Может, на вторую страницу, может к форме на этой. Мы не знаем.

2023-06-12 13:15 UTC, Ankhena commented on index.html
> +          <input class="subscribe-input" type="email" name="e-mail" placeholder="Ваш e-mail">
Не забудь придумать label ко всем инпутам.

2023-06-12 13:15 UTC, Ankhena commented on index.html
> +        <form class="subscribe-form" action="https://echo.htmlacademy.ru/" method="post">
Да, метод post - отлично!

2023-06-12 13:15 UTC, Ankhena commented on index.html
> +              <svg width="48" height="41" viewBox="0 0 48 41" fill="none" xmlns="http://www.w3.org/2000/svg">
Это из темы чуть подальше, но всё же:
Либо мы эти svg скрываем от читалок с помощью `aria-hidden="true"`
Либо (идеально) убираем в стили.

2023-06-12 13:15 UTC, Ankhena commented on index.html
> +        <h2 class="visually-hidden">Логотип .html academy</h2>
```suggestion
        <h2 class="visually-hidden">Логотип HTML Academy</h2>
```

2023-06-12 13:15 UTC, Ankhena commented on index.html
> +            alt=".html academy.">
```suggestion
          <img class="footer-logo-link-html" src="images/same/logo-htmlacademy.svg" width="115" height="33" lang="en"
            alt="HTML Academy.">
```

2023-06-12 13:15 UTC, Ankhena commented on catalog.html
> +      <header class="inner-header">
main - это основное содержимое страницы
header - шапка страницы

Так вот header от main это тот, который у тебя в 16 строке. 
Внутри main уже какой-то другой тег.

Раз этот тег нужен исключительно для того, чтобы

2023-06-12 13:15 UTC, Ankhena commented on catalog.html
> +      <header class="inner-header">
main - это основное содержимое страницы
header - шапка страницы

Так вот header от main это тот, который у тебя в 16 строке. 
Внутри main уже какой-то другой тег.

Раз этот тег нужен исключительно для того, чтобы задать фон, то это просто div.

2023-06-12 13:15 UTC, Ankhena commented on catalog.html
> +          </li>
```suggestion
          <li class="breadcrumbs-item">
            <a class="breadcrumbs-link breadcrumbs-link-icon" href="index.html">
              <span class="visually-hidden">Главная</span>
            </a>
          </li>
```

2023-06-12 13:15 UTC, Ankhena commented on catalog.html
> +          </li>
```suggestion
          <li class="breadcrumbs-item breadcrumbs-item-text">
            <a class="breadcrumbs-link breadcrumbs-link-text">Гостиницы</a>
          </li>
```

Последний пункт хлебных крошек это текущая страница. 
Таким образом, варианты:
1. Оставляем вообще просто текст внутри li
2. Меняем `a` на `span`
3.  Убираем href у `a`
4. Оставляем href и добавляем aria-current.

Мне наиболее симпатичными кажутся варианты 1 и 2. В меньшей мере 3.

2023-06-12 13:15 UTC, Ankhena commented on catalog.html
> +          </li>
```suggestion
          <li class="catalog-item">
            <a class="catalog-item-link" href="#">
              <img class="catalog-img" src="images/foto/page-2/hotel-1.jpg" width="300" height="212"
                alt="Невероятный вид на звездное небо.">
            </a>
            <h3 class="catalog-title">Amara Resort & Spa</h3>
            <p class="catalog-card-name">Гостиница</p>
            <p class="catalog-card-price">От 4000 ₽</p>
            <a class="button catalog-button-more" href="#">Подробнее</a>
            <button class="button catalog-button-favorite catalog-button-favorite-off" type="button">В
              избранное</button>

            <p class="stars star-4">
              <span class="visually-hidden">4 звезды</span>
            </p>
            <p class="catalog-rating">  
              Рейтинг: 8,5
            </p>
          </li>
```

2023-06-13 10:23 UTC, nknina commented on index.html
> +
Согласна, поправила наименование папок

2023-06-13 10:34 UTC, nknina commented on index.html
> +          <li class="navigation-item">
оставила в nav, исключила из списка

2023-06-13 12:34 UTC, nknina commented on index.html
> +          </li>
поправила

2023-06-13 12:35 UTC, nknina commented on index.html
> +          </li>
заменила на #

2023-06-13 12:38 UTC, nknina commented on index.html
> +          </li>
поняла свои ошибки :)

2023-06-13 12:59 UTC, nknina commented on catalog.html
> +      <header class="inner-header">
заменила header на div и для всего блока под фон. Header брала по примеру из барбершопа, видимо не так поняла

2023-06-13 12:59 UTC, nknina commented on catalog.html
> +      <header class="inner-header">
заменила header на div и для всего блока под фон. Header брала по примеру из барбершопа, видимо не так поняла

2023-06-13 13:02 UTC, nknina commented on catalog.html
> +          </li>
не совсем поняла. здесь удалить все svg?

2023-06-13 14:01 UTC, nknina commented on catalog.html
> +          </li>
-тег <b> использовала для указания важности информации, на одной из лекций было упомянуто это для выделения цены, заменила на <p>
-<buttom> первый заменила на <a> и добавила href
-знак рубля оставила по мнемонике
-рейтинг убрала в отдельный <p>

2023-06-13 14:31 UTC, nknina commented on index.html
> +            <p class="advantages-item-content advantages-white">Седона - не аттракцион для<br>туристов, там течёт
убрала <br>

2023-06-13 14:35 UTC, nknina commented on index.html
> +            </svg>
согласна, я в дальнейшем планировала их заменить, но для удобства "просмотра" готовности страницы добавила, чтобы понимать что получается)

2023-06-13 15:00 UTC, nknina commented on index.html
> +          <input class="subscribe-input" type="email" name="e-mail" placeholder="Ваш e-mail">
добавила

2023-06-13 15:05 UTC, nknina commented on catalog.html
> +          </li>
Все svg удалила, будут в стилях

2023-06-14 09:51 UTC, merged